version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personio_db
    ports:
      - "5432:5432"
    volumes:
      - /home/evandro/PostgreSQL-Volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "evandrormbrunassi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "personio"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
