version: '3'

services:
  personio-company-hierarchy:
    image: personio-company-hierarchy:1.0
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - postgres-compose-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
      - /home/evandro/personio/company-hierarchy:/logs
    depends_on:
      - postgres-compose
      - personio-login
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres-compose:5432/personio_db"    # Database url connection.

  personio-login:
    image: personio-login:1.0
    restart: unless-stopped
    ports:
      - "8081:8080"
    networks:
      - postgres-compose-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
      - /home/evandro/personio/login:/logs
    depends_on:
      - postgres-compose
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres-compose:5432/personio_db"    # Database url connection.


  postgres-compose:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personio_db
    ports:
      - "5432:5432"
    volumes:
      - /home/evandro/PostgreSQL-Volume:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "evandrormbrunassi@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "personio"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
